const FORMULARIO_PROYECTO = "PROYECTO_PROYECTO";
const OBTENER_PROYECTOS = "OBTENER_PROYECTOS";
const AGREGAR_PROYECTOS = "AGREGAR_PROYECTOS";
const VALIDAR_FORMULARIO = "VALIDAR_FORMULARIO";
const PROYECTO_ACTUAL = "PROYECTO_ACTUAL";
const ELIMINAR_PROYECTO = "ELIMINAR_PROYECTO";

const TAREAS_PROYECTO = "TAREAS_PROYECTO";
const AGREGAR_TAREA = "AGREGAR_TAREA";
const VALIDAR_TAREA = "VALIDAR_TAREA";
const ELIMINAR_TAREA = "ELIMINAR_TAREA";
const ESTADO_TAREA = "ESTADO_TAREA";

export {
  FORMULARIO_PROYECTO,
  OBTENER_PROYECTOS,
  AGREGAR_PROYECTOS,
  VALIDAR_FORMULARIO,
  PROYECTO_ACTUAL,
  ELIMINAR_PROYECTO,
  TAREAS_PROYECTO,
  AGREGAR_TAREA,
  VALIDAR_TAREA,
  ELIMINAR_TAREA,
  ESTADO_TAREA,
};
