const FORMULARIO_PROYECTO = "PROYECTO_PROYECTO";
const OBTENER_PROYECTOS = "OBTENER_PROYECTOS";
const AGREGAR_PROYECTOS = "AGREGAR_PROYECTOS";
const VALIDAR_FORMULARIO = "VALIDAR_FORMULARIO";
const PROYECTO_ACTUAL = "PROYECTO_ACTUAL";
const ELIMINAR_PROYECTO = "ELIMINAR_PROYECTO";
const PROYECTO_ERROR = "PROYECTO_ERROR";

const TAREAS_PROYECTO = "TAREAS_PROYECTO";
const AGREGAR_TAREA = "AGREGAR_TAREA";
const VALIDAR_TAREA = "VALIDAR_TAREA";
const ELIMINAR_TAREA = "ELIMINAR_TAREA";
const ESTADO_TAREA = "ESTADO_TAREA";
const TAREA_ACTUAL = "TAREA_ACTUAL";
const ACTUALIZAR_TAREA = "ACTUALIZAR_TAREA";
const LIMPIAR_TAREA = "LIMPIAR_TAREA";

const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
const OCULTAR_ALERTA = "OCULTAR_ALERTA";

const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
const REGISTRO_ERROR = "REGISTRO_ERROR";
const LOGIN_EXITOSO = "LOGIN_EXITOSO";
const LOGIN_ERROR = "LOGIN_ERROR";
const OBTENER_USUARIO = "OBTENER_USUARIO";
const CERRAR_SESION = "CERRAR_SESION";

export {
  FORMULARIO_PROYECTO,
  OBTENER_PROYECTOS,
  AGREGAR_PROYECTOS,
  VALIDAR_FORMULARIO,
  PROYECTO_ACTUAL,
  ELIMINAR_PROYECTO,
  TAREAS_PROYECTO,
  AGREGAR_TAREA,
  VALIDAR_TAREA,
  ELIMINAR_TAREA,
  ESTADO_TAREA,
  MOSTRAR_ALERTA,
  OCULTAR_ALERTA,
  REGISTRO_EXITOSO,
  REGISTRO_ERROR,
  LOGIN_EXITOSO,
  LOGIN_ERROR,
  OBTENER_USUARIO,
  CERRAR_SESION,
  PROYECTO_ERROR,
  TAREA_ACTUAL,
  ACTUALIZAR_TAREA,
  LIMPIAR_TAREA,
};
